"""
Django settings for ClearTrack project.

Generated by 'django-admin startproject' using Django 5.1.6.
"""

from pathlib import Path
import os

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-2c-hfd+r@#b8m9&twvg6xdwg52m_@d@le#^y6u^f^-n!44ic%8"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# ALLOWED HOSTS for Render subdomain
ALLOWED_HOSTS = ['.onrender.com']

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # Local apps
    "core",
    "accounts",
    "clearance",
    "dashboard",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # For static file handling
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middleware.TrialAndSubscriptionMiddleware",
    "accounts.middleware.subscription_middleware.SubscriptionMiddleware",
]

ROOT_URLCONF = "cleartrack.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cleartrack.wsgi.application"

# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Manila"
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files (uploaded images, QR codes, signatures)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Login URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Site URL (for QR generation and PayPal return URLs)
SITE_URL = 'https://cleartrack.onrender.com'  # Will work after deployment

# PayPal Settings
PAYPAL_MODE = 'sandbox'  # Change to 'live' in production
PAYPAL_CLIENT_ID = 'AbTgDTWEV3u0ijhMqeJ3zrgjRmol3b-aiPLxH-H1XKnIQ1B4WB_8nQFbSWTXVMgd8OUE4qgBknEjxz0T'
PAYPAL_CLIENT_SECRET = 'EFkEGB_hogOkUgdn3ggtQQMCh7pEU3xCx_Fi7rb7JRkLhBlwJjNY1RGJp5ZX1chfJBLgyv9xot8ucnel'

# Email Configuration (Gmail SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'danmugo42@gmail.com'       # Your Gmail address
EMAIL_HOST_PASSWORD = "wwvx narw xyaz sqcl"   # Gmail App Password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
