# Generated by Django 5.2.3 on 2025-06-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_plan_options_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['price_monthly'], 'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price',
        ),
        migrations.AddField(
            model_name='plan',
            name='price_monthly',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Monthly price in USD', max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='price_yearly',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Yearly price in USD', max_digits=8),
            preserve_default=False,
        ),
    ]
