# Generated by Django 5.2.3 on 2025-06-24 15:44

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_plan_options_remove_plan_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trial_ends_at',
            field=models.DateTimeField(default=billing.models.default_trial_end, help_text='End date for the 14-day free trial'),
        ),
    ]
