# Generated by Django 5.2.3 on 2025-07-01 06:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_has_active_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='has_active_subscription',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_end',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='trial_start',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('free_trial', 'Free Trial'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='free_trial', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trial_start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='auto_sign',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_landlord',
            field=models.BooleanField(default=False),
        ),
    ]
